---
- name: Creating skip argument
  set_fact:
    skipped_plugins: "--skip-plugins={{ SKIP_PLUGINS }}"
  when: SKIP_PLUGINS != ''

- name: Getting excluded tables
  shell: env




- name: Create template for extra extra_options
  template:
    src: extra_options.php.j2
    dest: /tmp/extra_options.php

- name: "Create {{ BACKUP_DIRECTORY }} directory"
  file:
    path: "{{ BACKUP_DIRECTORY }}"
    state: directory
    mode: "0755"

- name: "Exporting db"
  #shell:  wp db export {{ skipped_plugins }} --exclude_tables="$(wp db tables '{{ EXCLUDED_TABLES }}' {{ skipped_plugins }} --format=csv)" {{ BACKUP_DIRECTORY }}/backup_db-{{ ansible_date_time.date }}.sql >> {{ LOGFILE }}
  shell:  wp db export {{ skipped_plugins|quote }} --exclude_tables=wp_wfBadLeechers {{ BACKUP_DIRECTORY }}/backup_db-{{ ansible_date_time.date }}.sql >> {{ LOGFILE }}
  args:
    chdir: "{{ WORDPRESS_HOME }}"

- name: "Backing up files"
  archive:
    path:
      - "{{ WORDPRESS_HOME }}/wp-*"
      - "{{ WORDPRESS_HOME }}/*.php"
    dest: "{{ BACKUP_DIRECTORY }}/backup_files-{{ ansible_date_time.date }}.tar.bz2"
    format: bz2

- name: "Updating wordpress"
  shell:  wp core update {{ skipped_plugins }}  --require=/tmp/extra_options.php >> {{ LOGFILE }}
  args:
    chdir: "{{ WORDPRESS_HOME }}"

- name: "Updating db"
  shell:  wp core update-db {{ skipped_plugins }}  --require=/tmp/extra_options.php >> {{ LOGFILE }}
  args:
    chdir: "{{ WORDPRESS_HOME }}"

- name: "Updating plugins"
  shell:  wp plugin update --all {{ skipped_plugins }} --require=/tmp/extra_options.php >> {{ LOGFILE }}
  args:
    chdir: "{{ WORDPRESS_HOME }}"
  when: UPDATE_PLUGINS

- name: "Updating languages"
  shell:  wp core language update {{ skipped_plugins }} --require=/tmp/extra_options.php >> {{ LOGFILE }}
  args:
    chdir: "{{ WORDPRESS_HOME }}"
  when: UPDATE_LANGUAGE

- name: "Updating templates"
  shell:  wp theme update --all {{ skipped_plugins }} --require=/tmp/extra_options.php >> {{ LOGFILE }}
  args:
    chdir: "{{ WORDPRESS_HOME }}"
  when: UPDATE_TEMPLATES
